"""Generate CSS custom properties from shared_ui color and font tokens."""

from __future__ import annotations

from PyQt6.QtGui import QColor


def qcolor_to_hex(color: QColor) -> str:
    """Convert a QColor to a lowercase #rrggbb hex string."""
    return f"#{color.red():02x}{color.green():02x}{color.blue():02x}"


def collect_color_tokens() -> list[tuple[str, str]]:
    """Collect all QColor constants from colors.py as (--css-var, #hex) pairs."""
    from shared_ui import colors

    tokens = []
    for name in sorted(dir(colors)):
        if name.startswith("_"):
            continue
        val = getattr(colors, name)
        if isinstance(val, QColor):
            css_name = "--" + name.lower().replace("_", "-")
            tokens.append((css_name, qcolor_to_hex(val)))
    return tokens


_FONT_FAMILY_FALLBACKS = {
    "Segoe UI": '"Segoe UI", system-ui, sans-serif',
    "Cascadia Mono": '"Cascadia Mono", Consolas, monospace',
}


def collect_font_tokens() -> list[tuple[str, str]]:
    """Collect font families and size tiers from fonts.py as (--css-var, value) pairs."""
    from shared_ui import fonts

    tokens = []
    for name in sorted(dir(fonts)):
        if name.startswith("_"):
            continue
        val = getattr(fonts, name)
        if name.startswith("FONT_") and isinstance(val, str):
            if name == "FONT_MONO_FALLBACK":
                continue  # folded into FONT_MONO's fallback chain
            css_name = "--" + name.lower().replace("_", "-")
            tokens.append((css_name, _FONT_FAMILY_FALLBACKS.get(val, val)))
        elif name.startswith("SIZE_") and isinstance(val, int):
            css_name = "--" + name.lower().replace("_", "-")
            tokens.append((css_name, f"{val}px"))
    return tokens


def render_css(
    color_tokens: list[tuple[str, str]],
    font_tokens: list[tuple[str, str]],
) -> str:
    """Render CSS custom properties wrapped in a :root selector."""
    lines = [
        "/* Auto-generated by shared_ui/generate_web_tokens.py",
        " * Source: shared_ui/colors.py, shared_ui/fonts.py",
        " * Do not edit manually — regenerate with: npm run tokens:generate",
        " */",
        "",
        ":root {",
    ]
    for name, value in color_tokens:
        lines.append(f"  {name}: {value};")
    if color_tokens and font_tokens:
        lines.append("")
    for name, value in font_tokens:
        lines.append(f"  {name}: {value};")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    import argparse
    import sys

    parser = argparse.ArgumentParser(description="Generate CSS tokens from shared_ui")
    parser.add_argument("--output", help="Write to file instead of stdout")
    args = parser.parse_args()

    css = render_css(collect_color_tokens(), collect_font_tokens())

    if args.output:
        from pathlib import Path

        Path(args.output).write_text(css, encoding="utf-8")
    else:
        sys.stdout.write(css)


if __name__ == "__main__":
    main()
